<a href="https://colab.research.google.com/github/andrewbilbrey/DATA690-WANG/blob/master/assignments/Pandas_1aggregate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 07 - Pandas Aggregate

In [0]:
import numpy as np
import pandas as pd
import string

In [20]:
# builder pattern.
a = np.arange(100)
print(a)
b = a.reshape(10,10)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [2]:
# We start with a refresher on Numpy
# We have used rea-world data which is massive and messy.
# Let's generate small and simple dataset today
# create a list of 100 integers from 0 to 99 using Numpy arange 
# then reshape it to a 10 by 10 matrix (a list with 10 lists, each is a list of 10 integers)

x = np.arange(100).reshape(10,10)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [3]:
# Create a string of 26 alphabets (type str)
# turn a str into a list of 26 alphabets
# then only keep the fist 10 alphabets
# We will use the 10 alphabets as the column names for our dataframe

y = list(string.ascii_uppercase)[0:10]
y

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [4]:
# Create a data frame using x as the data and y as the column names
df = pd.DataFrame(x, columns=y)
df

A   B   C   D   E   F   G   H   I   J
0   0   1   2   3   4   5   6   7   8   9
1  10  11  12  13  14  15  16  17  18  19
2  20  21  22  23  24  25  26  27  28  29
3  30  31  32  33  34  35  36  37  38  39
4  40  41  42  43  44  45  46  47  48  49
5  50  51  52  53  54  55  56  57  58  59
6  60  61  62  63  64  65  66  67  68  69
7  70  71  72  73  74  75  76  77  78  79
8  80  81  82  83  84  85  86  87  88  89
9  90  91  92  93  94  95  96  97  98  99

In [25]:
df.sample(2)

A   B   C   D   E
11  20  14  81  44  77
13  92  71  75  43  22

In [5]:
# Use describe() method to produce summary statistics 
df.describe()

A          B          C  ...          H          I          J
count  10.000000  10.000000  10.000000  ...  10.000000  10.000000  10.000000
mean   45.000000  46.000000  47.000000  ...  52.000000  53.000000  54.000000
std    30.276504  30.276504  30.276504  ...  30.276504  30.276504  30.276504
min     0.000000   1.000000   2.000000  ...   7.000000   8.000000   9.000000
25%    22.500000  23.500000  24.500000  ...  29.500000  30.500000  31.500000
50%    45.000000  46.000000  47.000000  ...  52.000000  53.000000  54.000000
75%    67.500000  68.500000  69.500000  ...  74.500000  75.500000  76.500000
max    90.000000  91.000000  92.000000  ...  97.000000  98.000000  99.000000

[8 rows x 10 columns]

In [0]:
# The summary statistics does not include the sum of each column or each row 
# we would use aggregate() function


In [6]:
# By default, aggregate is over the rows 

df.aggregate("sum")

A    450
B    460
C    470
D    480
E    490
F    500
G    510
H    520
I    530
J    540
dtype: int64

In [7]:
# We can also aggregate over columns
# BTW, agg is an alias for aggregrate

df.agg("sum",axis="columns")

0     45
1    145
2    245
3    345
4    445
5    545
6    645
7    745
8    845
9    945
dtype: int64

In [8]:
# You can aggregate using multiple functions

df.agg(["sum", "median","std"])

A           B           C  ...           H           I           J
sum     450.000000  460.000000  470.000000  ...  520.000000  530.000000  540.000000
median   45.000000   46.000000   47.000000  ...   52.000000   53.000000   54.000000
std      30.276504   30.276504   30.276504  ...   30.276504   30.276504   30.276504

[3 rows x 10 columns]

In [9]:
# Here is another example with less data

df = pd.DataFrame([[1,2,3],
                  [4,5,6],
                  [7,8,9],
                  [np.nan, np.nan, np.nan]],
                  columns=["A", "B", "C"])
df

A    B    C
0  1.0  2.0  3.0
1  4.0  5.0  6.0
2  7.0  8.0  9.0
3  NaN  NaN  NaN

In [10]:
df.describe()

A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [11]:
df.aggregate(["min", "max", "sum", "mean"])

A     B     C
min    1.0   2.0   3.0
max    7.0   8.0   9.0
sum   12.0  15.0  18.0
mean   4.0   5.0   6.0

In [12]:
df.agg("min", axis="columns")

0    1.0
1    4.0
2    7.0
3    NaN
dtype: float64

In [13]:
# Here is another example using random numbers
# Generate 100 random integers ranging from 0 and 99
# reshape the one-dimensional numpy array into a 20 by 5 matrix (20 rows and 5 columns)

x = np.random.randint(0,100,100).reshape(20,5)
x

array([[ 1, 27, 54, 74, 97],
       [44, 53, 44, 30, 15],
       [36, 74, 97, 38, 34],
       [29, 43, 22, 99, 93],
       [60, 43, 17, 98,  6],
       [19, 65, 14, 76, 99],
       [97,  1, 46, 88, 11],
       [55, 16, 13, 50, 60],
       [73, 73, 69,  9, 98],
       [21, 53, 37, 29, 30],
       [95, 59, 45, 13, 82],
       [20, 14, 81, 44, 77],
       [53, 46, 67, 12, 58],
       [92, 71, 75, 43, 22],
       [41, 34, 79, 86, 84],
       [54, 83, 51, 73, 13],
       [77, 12, 28, 70, 85],
       [73, 22, 44, 22, 82],
       [80, 17, 59,  1, 45],
       [29, 84, 10, 96, 17]])

In [14]:
# Get the 26 alphabets using string library

y = string.ascii_uppercase
y

'ABCDEFGHIJKLMNOPQRSTUVWXYZ'

In [15]:
# Turn the str object into a list and keep only the first five 

y = list(y)[0:5]
y

['A', 'B', 'C', 'D', 'E']

In [16]:
# Create a dataframe using x and y

df = pd.DataFrame(x,columns=y)
df

A   B   C   D   E
0    1  27  54  74  97
1   44  53  44  30  15
2   36  74  97  38  34
3   29  43  22  99  93
4   60  43  17  98   6
5   19  65  14  76  99
6   97   1  46  88  11
7   55  16  13  50  60
8   73  73  69   9  98
9   21  53  37  29  30
10  95  59  45  13  82
11  20  14  81  44  77
12  53  46  67  12  58
13  92  71  75  43  22
14  41  34  79  86  84
15  54  83  51  73  13
16  77  12  28  70  85
17  73  22  44  22  82
18  80  17  59   1  45
19  29  84  10  96  17

In [0]:
# Calculate summary statistics 

In [18]:
df.describe()

A          B          C          D          E
count  20.000000  20.000000  20.000000  20.000000  20.000000
mean   52.450000  44.500000  47.600000  52.550000  55.400000
std    28.109701  25.730383  25.311533  32.735744  34.110347
min     1.000000   1.000000  10.000000   1.000000   6.000000
25%    29.000000  20.750000  26.500000  27.250000  20.750000
50%    53.500000  44.500000  45.500000  47.000000  59.000000
75%    74.000000  66.500000  67.500000  78.500000  84.250000
max    97.000000  84.000000  97.000000  99.000000  99.000000

In [0]:
# try pandas aggregate method here